#index:
#    path: /
#    controller: App\Controller\DefaultController::index

chooseMethod:
   path: /
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
   defaults: 
      template: 'chooseMethod.html.twig'

list:
   path: /
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
   defaults: 
      template: 'list.html.twig'