#index:
#    path: /
#    controller: App\Controller\DefaultController::index
   
chooseMethod:
   path: /choose
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
   defaults:
      template: 'chooseMethod.html.twig'