#index:
#    path: /
#    controller: App\Controller\DefaultController::index

chooseMethod:
   path: /choose
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
   defaults: 
      template: 'chooseMethod.html.twig'

list:
   path: /list
   controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
   defaults: 
      template: 'list.html.twig'
      
integerCheck:
   path: /integer
   controller: App\Controller\IntegerController::integerCheck